/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */

/**
 * Mapping of chainId to EncryptedDiceGame contract address
 */
export const encryptedDiceGameAddresses: Record<number, `0x${string}`> = {
  // Localhost/Hardhat Network
  31337: "0x5FbDB2315678afecb367f032d93F642f64180aa3",

  // Sepolia Testnet
  11155111: "0x76AE5b8D14FD8b725B5A0ef43145ce68e7829120",

  // Ethereum Mainnet (for future use)
  1: "0x0000000000000000000000000000000000000000",
} as const;

export function getEncryptedDiceGameAddress(
  chainId: number,
): `0x${string}` | undefined {
  return encryptedDiceGameAddresses[chainId];
}
